image: docker:git

services:
 - docker:dind

stages:
  - build

# Used to build release version of image
build_image_release:
  stage: build
  only:
  - /^v.*$/
  variables:
    IMAGE_NAME: opsbro/ops-bro
  before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - TAG_VERSION=$(echo $CI_COMMIT_REF_NAME | cut -d'v' -f 2)
  script:
  - docker build -t $IMAGE_NAME:$TAG_VERSION ./src
  - docker tag $IMAGE_NAME:$TAG_VERSION $IMAGE_NAME:latest
  - docker push $IMAGE_NAME:$TAG_VERSION
  - docker push $IMAGE_NAME:latest
  
# Used to build docker image per commit to develop  
build_image_develop:
  stage: build
  only:
  - develop
  variables:
    IMAGE_NAME: opsbro/ops-bro
  before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
  - docker build -t $IMAGE_NAME/develop:$CI_COMMIT_SHORT_SHA ./src
  - docker tag $IMAGE_NAME/develop:$CI_COMMIT_SHORT_SHA $IMAGE_NAME/develop:latest
  - docker push $IMAGE_NAME/develop:$CI_COMMIT_SHORT_SHA
  - docker push $IMAGE_NAME/develop:latest