image: docker:git

services:
 - docker:dind

stages:
  - build

build_backend_image:
  stage: build
  only:
  - /^v.*$/
  - develop
  variables:
    IMAGE_NAME: opsbro/ops-bro
  before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - TAG_VERSION=develop-$CI_COMMIT_SHORT_SHA
  script:
  - docker build -t $IMAGE_NAME:$TAG_VERSION ./src
  - docker push $IMAGE_NAME:$TAG_VERSION